### ISSUE TITLE
Refactoring is needed

### ISSUE THREAD

**Issue by kezif** [avsanek/Steam-Trade-Bot#2]
Friend you need to refactor your code really badly.
At first add `main.py` and `requirements.txt ` so people can have an idea how to launch your code.

Also check out my pull requests #1 It makes one function more readable but maybe it could give you a little headstart. Good luck tho.

**Comment by avsanek** [comment]
Brat welcome, thank for repeat yourself. We already Do what you say, but we need some test new featch. Wait a new upgrades ^)
